install:
	install -m 644 -D powerdown-functions $(DESTDIR)/lib/powerdown-functions
	install -D powerdown $(DESTDIR)/bin/powerdown
	install -D powerup $(DESTDIR)/bin/powerup
	install -D powernow $(DESTDIR)/bin/powernow
	install -D powerswitch $(DESTDIR)/bin/powerswitch
